"""Initial migration

Revision ID: d3ee2f4da2ca
Revises: 
Create Date: 2026-01-30 17:46:47.364845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
import src.db

# revision identifiers, used by Alembic.
revision: str = 'd3ee2f4da2ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit_type', postgresql.ENUM('CARDS', 'MINUTES', name='addon_unit_type_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('price_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('polar_product_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polar_product_id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_text')
    )
    op.create_table('notification_bar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('otpless_request_id', sa.String(), nullable=False),
    sa.Column('session_type', postgresql.ENUM('REGISTER', 'LOGIN', 'VERIFICATION', name='otp_session_type_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'VERIFIED', 'EXPIRED', 'FAILED', name='otp_status_enum'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_sessions_phone_expires', 'otp_sessions', ['phone_number', 'expires_at'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('chat_limit', sa.String(), nullable=True),
    sa.Column('card_limit', sa.Integer(), nullable=True),
    sa.Column('max_meditation_duration', sa.Integer(), nullable=True),
    sa.Column('is_audio', sa.Boolean(), nullable=False),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('polar_plan_id', sa.String(), nullable=True),
    sa.Column('plan_type', postgresql.ENUM('FREE', 'BASIC', 'PRO', name='plan_type_enum'), nullable=False),
    sa.Column('billing_cycle', postgresql.ENUM('MONTHLY', 'YEARLY', name='billing_cycle_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polar_plan_id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('PROCESSING', 'COMPLETED', 'FAILED', name='document_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_document_active', 'source_documents', ['active'], unique=False)
    op.create_index('idx_source_document_created_at', 'source_documents', ['created_at'], unique=False)
    op.create_index('idx_source_document_status', 'source_documents', ['status'], unique=False)
    op.create_index('idx_source_documents_active', 'source_documents', ['active', 'status'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('polar_customer_id', sa.String(), nullable=True),
    sa.Column('plan_type', postgresql.ENUM('FREE', 'BASIC', 'PRO', name='plan_type_enum'), nullable=True),
    sa.Column('customer_token', sa.String(), nullable=True),
    sa.Column('token_exp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polar_customer_id')
    )
    op.create_index(op.f('ix_user_profiles_auth_user_id'), 'user_profiles', ['auth_user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mark_as_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index('idx_conversation_deleted_at', 'conversations', ['deleted_at'], unique=False)
    op.create_index('idx_conversation_user_id', 'conversations', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_chunk_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_document_chunk_model', 'document_chunks', ['model_used'], unique=False)
    op.create_index('idx_document_chunk_source_id', 'document_chunks', ['source_document_id'], unique=False)
    op.create_table('plan_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_text', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_features_v1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_feature_link', 'plan_features_v1', ['plan_id', 'feature_id'], unique=True)
    op.create_table('plan_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('polar_price_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polar_price_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('polar_subscription_id', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', name='subscription_status_enum'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polar_subscription_id')
    )
    op.create_index('idx_subscription_polar_id', 'subscriptions', ['polar_subscription_id'], unique=False)
    op.create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscription_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('polar_order_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polar_order_id')
    )
    op.create_index('idx_transaction_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_transaction_user_id', 'transactions', ['user_id'], unique=False)
    op.create_table('user_addons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.Column('polar_order_id', sa.String(), nullable=True),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('used_value', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addon_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_addon_status', 'user_addons', ['status'], unique=False)
    op.create_index('idx_user_addon_user_id', 'user_addons', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_type', postgresql.ENUM('POSITIVE', 'NEGATIVE', name='feedback_type_enum'), nullable=True),
    sa.Column('feedback_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_message_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_feedback_type', 'messages', ['feedback_type'], unique=False)
    op.create_index('idx_message_role', 'messages', ['role'], unique=False)
    op.create_table('subscription_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('previous_plan_id', sa.Integer(), nullable=True),
    sa.Column('polar_subscription_id', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', name='subscription_status_enum'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['previous_plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sub_history_subscription_id', 'subscription_history', ['subscription_id'], unique=False)
    op.create_index('idx_sub_history_user_id', 'subscription_history', ['user_id'], unique=False)
    op.create_table('content_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('content_type', postgresql.ENUM('IMAGE', 'VIDEO', 'AUDIO', name='content_type_enum'), nullable=False),
    sa.Column('content_path', sa.String(), nullable=True),
    sa.Column('cc_text', sa.Text(), nullable=True),
    sa.Column('cc_theme', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_generation_conversation_id', 'content_generations', ['conversation_id'], unique=False)
    op.create_index('idx_content_generation_created_at', 'content_generations', ['created_at'], unique=False)
    op.create_index('idx_content_generation_message_id', 'content_generations', ['message_id'], unique=False)
    op.create_index('idx_content_generation_type', 'content_generations', ['content_type'], unique=False)
    op.create_index('idx_content_generation_user_id', 'content_generations', ['user_id'], unique=False)
    op.create_index('idx_content_generations_type', 'content_generations', ['content_type'], unique=False)
    op.create_index('idx_content_generations_user_created', 'content_generations', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_content_generations_user_created', table_name='content_generations')
    op.drop_index('idx_content_generations_type', table_name='content_generations')
    op.drop_index('idx_content_generation_user_id', table_name='content_generations')
    op.drop_index('idx_content_generation_type', table_name='content_generations')
    op.drop_index('idx_content_generation_message_id', table_name='content_generations')
    op.drop_index('idx_content_generation_created_at', table_name='content_generations')
    op.drop_index('idx_content_generation_conversation_id', table_name='content_generations')
    op.drop_table('content_generations')
    op.drop_index('idx_sub_history_user_id', table_name='subscription_history')
    op.drop_index('idx_sub_history_subscription_id', table_name='subscription_history')
    op.drop_table('subscription_history')
    op.drop_index('idx_message_role', table_name='messages')
    op.drop_index('idx_message_feedback_type', table_name='messages')
    op.drop_index('idx_message_created_at', table_name='messages')
    op.drop_index('idx_message_conversation_id', table_name='messages')
    op.drop_index('idx_message_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_user_addon_user_id', table_name='user_addons')
    op.drop_index('idx_user_addon_status', table_name='user_addons')
    op.drop_table('user_addons')
    op.drop_index('idx_transaction_user_id', table_name='transactions')
    op.drop_index('idx_transaction_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_subscription_user_id', table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.drop_index('idx_subscription_polar_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('plan_prices')
    op.drop_index('idx_plan_feature_link', table_name='plan_features_v1')
    op.drop_table('plan_features_v1')
    op.drop_table('plan_features')
    op.drop_index('idx_document_chunk_source_id', table_name='document_chunks')
    op.drop_index('idx_document_chunk_model', table_name='document_chunks')
    op.drop_index('idx_document_chunk_embedding', table_name='document_chunks', postgresql_using='ivfflat')
    op.drop_table('document_chunks')
    op.drop_index('idx_conversation_user_id', table_name='conversations')
    op.drop_index('idx_conversation_deleted_at', table_name='conversations')
    op.drop_index('idx_conversation_created_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_user_profiles_auth_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('idx_source_documents_active', table_name='source_documents')
    op.drop_index('idx_source_document_status', table_name='source_documents')
    op.drop_index('idx_source_document_created_at', table_name='source_documents')
    op.drop_index('idx_source_document_active', table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_table('plans')
    op.drop_index('idx_otp_sessions_phone_expires', table_name='otp_sessions')
    op.drop_table('otp_sessions')
    op.drop_table('notification_bar')
    op.drop_table('features')
    op.drop_table('addon_types')
    # ### end Alembic commands ###
