"""add_is_active_to_user_profiles

Revision ID: 863df6d72f57
Revises: d3ee2f4da2ca
Create Date: 2026-02-13 15:33:03.178969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863df6d72f57'
down_revision: Union[str, Sequence[str], None] = 'd3ee2f4da2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'is_active')
    # ### end Alembic commands ###
